AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - spec/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 50

Naming/FileName:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false
