AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - spec/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Naming/FileName:
  Enabled: false

Style/HashSyntax:
  Enabled: false
